import numpy as np

a = np.array([0, 1, 2])
b = np.array([0, 4])
aa, bb = np.meshgrid(a, b)
print(aa)
print("-" * 30)
print(bb)
print("-" * 30)

c = np.array([0, 9])
aaa, bbb, ccc = np.meshgrid(a, b, c)
print(aaa)
print("-" * 30)
print(bbb)
print("-" * 30)
print(ccc)
print("#" * 30)

aa2, bb2 = np.meshgrid(a, b, indexing='xy')
print(aa2)
print("-" * 30)
print(bb2)
print("-" * 30)

aa3, bb3 = np.meshgrid(a, b, indexing='ij')
print(aa3)
print("-" * 30)
print(bb3)
print("-" * 30)

aaa1, bbb1, ccc1 = np.meshgrid(a, b, c, indexing='xy')
print(aaa1)
print("-" * 30)
print(bbb1)
print("-" * 30)
print(ccc1)
print("-" * 30)

aaa2, bbb2, ccc2 = np.meshgrid(a, b, c, indexing='ij')
print(aaa2)
print("-" * 30)
print(bbb2)
print("-" * 30)
print(ccc2)
print("#" * 30)

av, bv = np.meshgrid(a, b, sparse=True)
print(av)
print("-" * 30)
print(bv)
print("-" * 30)

aav, bbv, ccv = np.meshgrid(a, b, c, sparse=True)
print(aav)
print("-" * 30)
print(bbv)
print("-" * 30)
print(ccv)
